# Generated by Django 5.2.5 on 2025-08-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField()),
                ('cost_center_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Dump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('godown_name', models.CharField(max_length=255)),
                ('dump_name', models.CharField(max_length=255)),
                ('sales_hub', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Godown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('godown_name', models.CharField(max_length=255)),
                ('godown_ghat', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=15)),
                ('type', models.CharField(choices=[('self', 'Self'), ('medium', 'Medium')], max_length=20)),
                ('sales_hub', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('product_group', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=50)),
                ('unit_type', models.CharField(max_length=50)),
                ('unit_strength', models.CharField(max_length=50)),
                ('open_sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('allotment_sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable')], default='available', max_length=20)),
            ],
        ),
    ]
