# Generated by Django 5.2.5 on 2025-08-28 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Supplier Name')),
                ('contact', models.CharField(max_length=15, verbose_name='Contact')),
                ('address', models.TextField(verbose_name='Address')),
                ('district', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=255)),
                ('status', models.CharField(default='active', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('purchase_id', models.CharField(default='', max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('audited', 'Audited'), ('approved', 'Approved')], default='pending', max_length=20)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchasemanage.supplier')),
            ],
        ),
    ]
