# Generated by Django 5.2.5 on 2025-08-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consignee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consignee_type', models.CharField(choices=[('local', 'Local'), ('overseas', 'Overseas'), ('both', 'Both')], default='local', max_length=20)),
                ('consignee_name', models.CharField(max_length=255)),
                ('owner_name', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=15)),
                ('reg_number', models.CharField(max_length=50)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lc_number', models.CharField(max_length=100, unique=True)),
                ('mv', models.CharField(max_length=255, verbose_name='Mother Vessel')),
                ('allot_lc', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=255)),
                ('consignee', models.CharField(max_length=255)),
                ('bank_info', models.CharField(max_length=255)),
                ('entry_date', models.DateField(auto_now_add=True)),
                ('lc_date', models.DateField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('select_status', 'Select Status'), ('running', 'Running'), ('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive')], default='select_status', max_length=20)),
                ('lc_account', models.CharField(blank=True, max_length=100, null=True)),
                ('lc_bank', models.CharField(blank=True, max_length=255, null=True)),
                ('lc_bank_branch', models.CharField(blank=True, max_length=255, null=True)),
                ('exporter_info', models.CharField(blank=True, max_length=255, null=True)),
                ('registration_no', models.CharField(blank=True, max_length=100, null=True)),
                ('exporter_country', models.CharField(blank=True, max_length=100, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('lc_open_date', models.DateField(blank=True, null=True)),
                ('sale_status', models.CharField(choices=[('select_status', 'Select Status'), ('running', 'Running'), ('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive')], default='select_status', max_length=20)),
            ],
        ),
    ]
