# Generated by Django 5.2.5 on 2025-08-28 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(default=10000000, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('voucher_number', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trn_id', models.CharField(max_length=50)),
                ('account_debit', models.CharField(max_length=100)),
                ('account_credit', models.CharField(max_length=100)),
                ('lc_number', models.CharField(max_length=100)),
                ('note', models.TextField(blank=True)),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='journalmanage.journal')),
            ],
        ),
    ]
